apiVersion: skaffold/v1beta6
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: postput/admin-backend
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: postput-backend
        chartPath: chart
        #wait: true
        #recreatePods: true
        #valuesFiles:
        #- helm-skaffold-values.yaml
        values:
          imageOverride: postput/admin-backend
